### ISSUE TITLE
Error during deployment

### ISSUE THREAD

**Issue by dxs-dbest** [jowavp/sap-cf-axios-example#2]
I am getting an error when the sca_srv application is starting.  Any advice on how to run this example?

`

25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | npm ERR!
-- | -- | -- | --
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | npm ERR! code ELIFECYCLE
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | npm ERR! errno 1
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | /home/vcap/app/index.js:10
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | const dummy = SapCfAxios('GW');
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | ^
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | TypeError: SapCfAxios is not a function
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | at Object.<anonymous> (/home/vcap/app/index.js:10:15)
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | at Module._compile (internal/modules/cjs/loader.js:778:30)
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | at Module.load (internal/modules/cjs/loader.js:653:32)
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | at Function.Module._load (internal/modules/cjs/loader.js:585:3)
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | at startup (internal/bootstrap/node.js:283:19)
25 Feb 2020, 13:11:09 (GMT-05:00) | STDERR | [APP/PROC/WEB/0] | at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

`

**Comment by dxs-dbest** [comment]
I was able to deploy the application after changing line 11 of srv/index.js to the following:
`const dummy = SapCfAxios.default('dummy');`
